project/apps/CORE/urls.py
from django.urls import path
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from . import views
from .views import home, crear_cliente, busqueda

app_name = "Home"

urlpatterns = [
 #   path('', views.index),
    path("", home, name="home"),
    path("clientes/", views.clientes, name="clientes"),
    path('crear/', crear_cliente, name="crear"),
    path('busqueda/', busqueda, name="busqueda"),
]

urlpatterns += staticfiles_urlpatterns()
### Esto sirve para poder usar los archivos de static
### desde los HTML o templates

project/config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("CORE.urls")),
]

project/apps/CORE/models.py
from django.db import models

# Create your models here.

class Pais(models.Model):
    nombre=models.CharField(max_length=50)

    def __str__(self):
        return self.nombre

class Mediodepago(models.Model):
    medio=models.CharField(max_length=25)

    def __str__(self):
        return self.medio

class Cliente(models.Model):
    pais_origen_id=models.ForeignKey(Pais, on_delete=models.SET_NULL, null=True)
    apellido=models.CharField(max_length=50)
    nombre=models.CharField(max_length=50)
    nacimiento= models.DateField(null=True) # opcional
    medio_id=models.ForeignKey(Mediodepago, on_delete=models.SET_NULL, null=True)
    nrotarjeta=models.IntegerField(null=True)

    def __str__(self):
        return f"{self.nombre} {self.apellido}. Nació el {self.nacimiento} en {self.pais_origen_id}. Paga a través de {self.medio_id} Nro. {self.nrotarjeta}"

project/apps/CORE/forms.py
from django import forms
from .models import Cliente

 
class ClienteForm(forms.ModelForm):
    class Meta:
        model = Cliente
        fields = ["pais_origen_id", "apellido", "nombre", "nacimiento", "medio_id", "nrotarjeta"]

project/apps/CORE/views.py
from datetime import date

from django.http import HttpRequest, HttpResponse
from django.shortcuts import redirect, render
#from django.urls import is_valid_path
from .forms import ClienteForm

# Create your views here.
from .models import Cliente, Mediodepago, Pais

def home(request):
    return render(request, "CORE/index.html")

def clientes(request):
    clientes_registros = Cliente.objects.all()
    contexto = {"clientes": clientes_registros}
    # return render(request, "index.html", {"clientes": clientes_registros})
    return render(request, "CORE/clientes.html", contexto)


def crear_cliente(request: HttpRequest) -> HttpResponse:
    if request.method == "POST":
        form = ClienteForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect("Home:clientes")
    else:  # request.method == "GET"
        form = ClienteForm()
    return render(request, "CORE/crear.html", {"form": form})


def busqueda(request: HttpRequest) -> HttpResponse:
    # Búsqueda por nombre que contenga "M"
    cliente_nombre = Cliente.objects.filter(nombre__contains="M")

    # Nacimientos  mayores a 2005
    cliente_nacimiento = Cliente.objects.filter( nacimiento__lt=date(2005, 1, 1))

    #age = date.today().year - nacimiento.year - ((date.today().month, date.today().day) < (nacimiento.month, nacimiento.day))

    #cliente_nacimiento = Cliente.objects.filter((date.today().year - nacimiento.year - ((date.today().month, date.today().day) < (nacimiento.month, nacimiento.day)))__gte=18)

    # País de origen vacío
    cliente_pais = Cliente.objects.filter(pais_origen_id=1)

    contexto = {
        "clientes_nombre": cliente_nombre,
        "clientes_nacimiento": cliente_nacimiento,
        "clientes_pais": cliente_pais
    }
    return render(request, "CORE/busqueda.html", contexto)

project/apps/CORE/templates/CORE/base.html
{% load static %}

<!DOCTYPE html>
<html lang="es">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <h1 style="color:purple;"></h1><title>Tienda</title></h1>
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="{% static 'CORE/assets/favicon.png' %}" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static 'CORE/css/styles.css' %}" rel="stylesheet" />
    </head>
    <body>
        <!-- Responsive navbar-->
        {% include 'CORE/navbar.html' %}

        <!-- Page Content-->
        <div class="container px-4 px-lg-5">

            {% block BASE_CONTENIDO %}
                
            {% endblock BASE_CONTENIDO %}


            <!-- Call to Action-->
 <!--            <div class="card text-white bg-secondary my-5 py-4 text-center">
                <div class="card-body"><p class="text-white m-0">This call to action card is a great place to showcase some important information or display a clever tagline!</p></div>
            </div>-->

        </div>
        <!-- Footer-->
        {% include 'CORE/footer.html' %}
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="{% static 'CORE/js/scripts.js' %}"></script>
    </body>
</html>

project/apps/CORE/templates/CORE/busqueda.html
{% extends 'CORE/index.html' %}

{% block INDEX_TITULO %} 
    Búsquedas
{% endblock INDEX_TITULO %}

{% block INDEX_CONTENIDO %}

    <h2> Clientes cuyo nombre contiene 'm'</h2>
    {% for cliente in clientes_nombre %}
        <p>{{ cliente }}</p>
    {% endfor %}

    <h2> Cliente cuyo nacimiento es antes de 2005 (mayor de edad) </h2>
    {% for cliente in clientes_nacimiento %}
        <p> {{ cliente }}</p>
    {% endfor %}

    <h2> Clientes de Argentina  </h2>
    {% for cliente in clientes_pais %}
        <p> {{ cliente }}</p>
    {% endfor %}

    <a href="{% url 'Home:home' %}">Ir al menú principal</a>

{% endblock INDEX_CONTENIDO %}

project/apps/CORE/templates/CORE/card.html
<div class="col-md-4 mb-5">
    <div class="card h-100">
        <div class="card-body">
            <h2 class="card-title">{{ card }}</h2>
            <p class="card-text">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Rem magni quas ex numquam, maxime minus quam molestias corporis quod, ea minima accusamus.</p>
        </div>
        <div class="card-footer"><a class="btn btn-primary btn-sm" href="#!">Más información</a></div>
    </div>
</div>

project/apps/CORE/templates/CORE/clientes.html
{% extends 'CORE/index.html' %}

 
{% block INDEX_TITULO %} 
    Clientes
{% endblock INDEX_TITULO %}

{% block INDEX_CONTENIDO %}

    {% for cliente in clientes %}

    <h1>{{ cliente.nombre }} {{ cliente.apellido }}</h1>
    <p>Nació el {{ cliente.nacimiento }} en {{ cliente.pais_origen_id }}.</p>
    <p>Paga a través de {{ cliente.medio_id }} Nro {{ cliente.nrotarjeta }}.</p>

    {% endfor %}

    <a href="{% url 'Home:home' %}">Ir al menú principal</a>

{{ saludo }}
{% endblock INDEX_CONTENIDO %}

project/apps/CORE/templates/CORE/crear.html
{% extends 'Core/index.html' %}

{% block INDEX_TITULO %} 
    Crear Cliente
{% endblock INDEX_TITULO %}

{% block INDEX_CONTENIDO %}

    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Guardar</button>
    </form>
    <br>
    <a href="{% url 'Home:home' %}">Ir al menú principal</a>

{% endblock INDEX_CONTENIDO %}

project/apps/CORE/templates/CORE/footer.html
<footer class="bg-dark fixed-bottom ">
    <div class="container px-4 px-lg-5"><p class="m-0 text-center text-white">Copyright &copy; Iripop 2023</p></div>
</footer>

project/apps/CORE/templates/CORE/index.html
{% extends 'CORE/base.html' %}

{% load static %}

{% block BASE_CONTENIDO %}

<div class="row align-items-center my-5">
    <h1 class="pb-lg-3 text-bg-light">
        {% block INDEX_TITULO %}
            Página de inicio
        {% endblock INDEX_TITULO %}
    </h1>
</div>

    {% block INDEX_CONTENIDO %}

    <!-- Heading Row-->
    <div class="row gx-4 gx-lg-5 align-items-center my-5">
        <div class="col-lg-7"><img class="img-fluid rounded mb-4 mb-lg-0" src="{% static 'CORE/img/fotoppal.png' %}" alt="..." /></div>
        <div class="col-lg-5">
            <h1 class="font-weight-light">Tienda</h1>
            <p>Descripción del negocio</p>
            <h1 style="color:#25D366;"><a class="btn btn-primary" href="https://wa.me/5491100000000" target="_blank">WhatsApp</a></h1>
        </div>
    </div>

    <!-- Content Row-->
    <div class="row gx-4 gx-lg-5">

        {% include 'CORE/card.html' with card="Tarjeta 1" %}
        {% include 'CORE/card.html' with card="Tarjeta 2" %}
        {% include 'CORE/card.html' with card="Tarjeta 3" %}


    
    </div>

    {% endblock INDEX_CONTENIDO %}
    
{% endblock BASE_CONTENIDO %}

project/apps/CORE/templates/CORE/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container px-5">
        <a class="navbar-brand" href="#!">Tienda</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                <li class="nav-item"><a class="nav-link active" aria-current="page" href="Home:home">Home</a></li>
                <li class="nav-item"><a class="nav-link" href="#!">Contacto</a></li>
                <li class="nav-item"><a class="nav-link" href="#!">Sobre nosotros</a></li>
                <li class="nav-item"><a class="nav-link" href="{% url 'Home:clientes' %}">Clientes</a></li>
                <li class="nav-item"><a class="nav-link" href="{% url 'Home:crear' %}">Crear</a></li>
                <li class="nav-item"><a class="nav-link" href="{% url 'Home:busqueda' %}">Busqueda</a></li>

            </ul>
        </div>
    </div>
</nav>

project/apps/CORE/templates/CORE/search.html
{% extends 'Core/base.html' %}

{% block TITULO %} 
    Búsquedas
{% endblock TITULO %}

{% block CONTENIDO %}

    <h2> Clientes cuyo nombre contiene 'm'</h2>
    {% for cliente in clientes_nombre %}
        <p>{{ cliente }}</p>
    {% endfor %}

    <h2> Cliente cuyo nacimiento es antes de 2005 (mayor de edad) </h2>
    {% for cliente in clientes_nacimiento %}
        <p> {{ cliente }}</p>
    {% endfor %}

    <h2> Clientes de Argentina  </h2>
    {% for cliente in clientes_pais %}
        <p> {{ cliente }}</p>
    {% endfor %}

    <a href="{% url 'Home:home' %}">Ir al menú principal</a>

{% endblock CONTENIDO %}